// Shape matches Track4/intern_i_backend_engine schemas.ScriptResultResponse.
// Used so the dashboard is developable/demoable before the live pipeline
// is wired end-to-end.
export const sampleScript = {
  script_id: "script_014",
  student_id: "masked",
  page_image_url: "/sample-script.jpg",
  image_width: 1024,
  image_height: 1365,
  total_score: 21.5,
  total_max_score: 30,
  questions: [
    {
      question_id: "Q1",
      course_outcome: "CO2",
      answer_type: "diagram",
      programmatic_score: 7,
      max_score: 10,
      final_score: 7,
      llm_confidence: "medium",
      c_global: 0.78,
      confidence_components: { vision: 0.91, extraction: 0.72, graph: 0.7, llm: 0.6 },
      human_review_required: true,
      review_reason: "C_global below threshold (0.78 < 0.85)",
      feedback:
        "Topology is mostly correct — router and switch are connected as expected, but the firewall node is missing an edge to the server.",
      detected_errors: ["Missing edge: Firewall → Server"],
      structural_payload: {
        nodes: [
          { id: "v0", type: "Router" },
          { id: "v1", type: "Switch" },
          { id: "v2", type: "Firewall" },
          { id: "v3", type: "Server" },
        ],
        edges: [
          ["v0", "v1"],
          ["v1", "v2"],
        ],
      },
      bounding_boxes: [{ x0: 62, y0: 120, x1: 480, y1: 360, region_type: "diagram" }],
    },
    {
      question_id: "Q2",
      course_outcome: "CO3",
      answer_type: "code",
      programmatic_score: 9,
      max_score: 10,
      final_score: 9,
      llm_confidence: "high",
      c_global: 0.93,
      confidence_components: { vision: 0.95, extraction: 0.94, llm: 1.0 },
      human_review_required: false,
      review_reason: null,
      feedback: "Correct binary search implementation. Minor: off-by-one risk if array is empty, not penalized.",
      detected_errors: [],
      structural_payload: {
        language: "python",
        ast_summary: "FunctionDef(binary_search) -> While loop, 2 branches, 1 return",
      },
      bounding_boxes: [{ x0: 62, y0: 400, x1: 480, y1: 620, region_type: "code" }],
    },
    {
      question_id: "Q3",
      course_outcome: "CO1",
      answer_type: "math",
      programmatic_score: 5.5,
      max_score: 10,
      final_score: 5.5,
      llm_confidence: "low",
      c_global: 0.54,
      confidence_components: { vision: 0.88, extraction: 0.41, llm: 0.3 },
      human_review_required: true,
      review_reason: "Low transcription confidence on handwritten derivation",
      feedback: "First two steps match the reference derivation; step 3 onward could not be confidently transcribed.",
      detected_errors: ["Low OCR confidence past step 2", "Final answer not detected"],
      structural_payload: { latex_partial: "\\frac{d}{dx}(x^2 + 3x) = 2x + 3", steps_validated: 2, steps_total: 5 },
      bounding_boxes: [{ x0: 520, y0: 120, x1: 960, y1: 400, region_type: "math" }],
    },
  ],
};
